### PR TITLE
chore/merge go 1.15

### PR DESCRIPTION
**Pull request by lwaddicor**
This merges in the changes to the winsvc library that are in the main fork of this library.

There have been alot of changes but it appears the service.go file which handles the pre shutdown is untouched so the changes merged ok.

This merges in the release branch for go 1.15 of the winsvc repo.

### CODE REVIEW

**Comment by lwaddicor** [comment]
Panic which was shown before:
```
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xf135acb8 pc=0x1424990]

goroutine 34 [running]:
runtime.throw(0x154fa13, 0x5)
	/downloads/go/src/runtime/panic.go:1116 +0x79 fp=0xc00037bda8 sp=0xc00037bd78 pc=0xefaa39
runtime.sigpanic()
	/downloads/go/src/runtime/signal_windows.go:249 +0x24f fp=0xc00037bdd8 sp=0xc00037bda8 pc=0xf0f72f
github.com/multiplay/winsvc/svc.(*service).run(0xc00030c500)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:198 +0x70 fp=0xc00037bfd8 sp=0xc00037bdd8 pc=0x1424990
runtime.goexit()
	/downloads/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00037bfe0 sp=0xc00037bfd8 pc=0xf311e1
created by github.com/multiplay/winsvc/svc.Run
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:316 +0x1b2

goroutine 1 [syscall, locked to thread]:
syscall.Syscall(0x7ffbe12c6580, 0x1, 0xc00019fda0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/downloads/go/src/runtime/syscall_windows.go:188 +0xe9
github.com/multiplay/winsvc/winapi.StartServiceCtrlDispatcher(0xc00019fda0, 0x157d010, 0xc00030c500)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/winapi/zwinapi_windows.go:257 +0x8c
github.com/multiplay/winsvc/svc.Run(0x155402a, 0xa, 0x164cb60, 0xc00032c240, 0x0, 0x0)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:318 +0x1c5
github.com/multiplay/go/service.(*winManager).Run(0xc00032c240, 0x0, 0x0)
	/go/src/github.com/multiplay/go/service/service_windows.go:220 +0x82
github.com/multiplay/go/service.(*Service).Process(0xc0003061b0, 0x0, 0x0, 0xc0003061c0, 0xc0003002a0)
	/go/src/github.com/multiplay/go/service/service.go:123 +0x10c
github.com/multiplay/go/service.(*Generic).Run(0xc000310100, 0x0, 0x0)
	/go/src/github.com/multiplay/go/service/generic.go:228 +0x9c
github.com/multiplay/go/service.(*Generic).LoadConfigAndRun(0xc000310100, 0xc00031a0f0, 0x155402a)
	/go/src/github.com/multiplay/go/service/generic.go:237 +0x67
github.com/multiplay/go/service.RunGeneric(0x1651720, 0xc00031a0f0, 0x155402a, 0xa, 0x155b811, 0x14, 0x156ef68, 0x31, 0x1480d00, 0xc0003141a0)
	/go/src/github.com/multiplay/go/service/generic.go:145 +0xc5
main.main()
	/go/src/github.com/multiplay/go/apps/gameserver/gameserver.go:287 +0xd0
unexpected fault address 0x65ba4f8
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x65ba4f8 pc=0x1424990]

goroutine 5 [running]:
runtime.throw(0x154fa13, 0x5)
	/downloads/go/src/runtime/panic.go:1116 +0x79 fp=0xc000059da8 sp=0xc000059d78 pc=0xefaa39
runtime.sigpanic()
	/downloads/go/src/runtime/signal_windows.go:249 +0x24f fp=0xc000059dd8 sp=0xc000059da8 pc=0xf0f72f
github.com/multiplay/winsvc/svc.(*service).run(0xc00005a580)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:198 +0x70 fp=0xc000059fd8 sp=0xc000059dd8 pc=0x1424990
runtime.goexit()
	/downloads/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000059fe0 sp=0xc000059fd8 pc=0xf311e1
created by github.com/multiplay/winsvc/svc.Run
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:316 +0x1b2

goroutine 1 [syscall, locked to thread]:
syscall.Syscall(0x7ffbe12c6580, 0x1, 0xc00019fda0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/downloads/go/src/runtime/syscall_windows.go:188 +0xe9
github.com/multiplay/winsvc/winapi.StartServiceCtrlDispatcher(0xc00019fda0, 0x157d010, 0xc00005a580)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/winapi/zwinapi_windows.go:257 +0x8c
github.com/multiplay/winsvc/svc.Run(0x155402a, 0xa, 0x164cb60, 0xc000074300, 0x0, 0x0)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:318 +0x1c5
github.com/multiplay/go/service.(*winManager).Run(0xc000074300, 0x0, 0x0)
	/go/src/github.com/multiplay/go/service/service_windows.go:220 +0x82
github.com/multiplay/go/service.(*Service).Process(0xc0000501d0, 0x0, 0x0, 0xc0000501e0, 0xc000022360)
	/go/src/github.com/multiplay/go/service/service.go:123 +0x10c
github.com/multiplay/go/service.(*Generic).Run(0xc000060100, 0x0, 0x0)
	/go/src/github.com/multiplay/go/service/generic.go:228 +0x9c
github.com/multiplay/go/service.(*Generic).LoadConfigAndRun(0xc000060100, 0xc00005c140, 0x155402a)
	/go/src/github.com/multiplay/go/service/generic.go:237 +0x67
github.com/multiplay/go/service.RunGeneric(0x1651720, 0xc00005c140, 0x155402a, 0xa, 0x155b811, 0x14, 0x156ef68, 0x31, 0x1480d00, 0xc0000641a0)
	/go/src/github.com/multiplay/go/service/generic.go:145 +0xc5
main.main()
	/go/src/github.com/multiplay/go/apps/gameserver/gameserver.go:287 +0xd0
unexpected fault address 0x1de6ac38
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x1de6ac38 pc=0x1424990]

goroutine 20 [running]:
runtime.throw(0x154fa13, 0x5)
	/downloads/go/src/runtime/panic.go:1116 +0x79 fp=0xc000055da8 sp=0xc000055d78 pc=0xefaa39
runtime.sigpanic()
	/downloads/go/src/runtime/signal_windows.go:249 +0x24f fp=0xc000055dd8 sp=0xc000055da8 pc=0xf0f72f
github.com/multiplay/winsvc/svc.(*service).run(0xc0001f7200)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:198 +0x70 fp=0xc000055fd8 sp=0xc000055dd8 pc=0x1424990
runtime.goexit()
	/downloads/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000055fe0 sp=0xc000055fd8 pc=0xf311e1
created by github.com/multiplay/winsvc/svc.Run
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:316 +0x1b2

goroutine 1 [syscall, locked to thread]:
syscall.Syscall(0x7ffbe12c6580, 0x1, 0xc00019fda0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/downloads/go/src/runtime/syscall_windows.go:188 +0xe9
github.com/multiplay/winsvc/winapi.StartServiceCtrlDispatcher(0xc00019fda0, 0x157d010, 0xc0001f7200)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/winapi/zwinapi_windows.go:257 +0x8c
github.com/multiplay/winsvc/svc.Run(0x155402a, 0xa, 0x164cb60, 0xc0002b2720, 0x0, 0x0)
	/go/src/github.com/multiplay/go/vendor/github.com/multiplay/winsvc/svc/service.go:318 +0x1c5
github.com/multiplay/go/service.(*winManager).Run(0xc0002b2720, 0x0, 0x0)
	/go/src/github.com/multiplay/go/service/service_windows.go:220 +0x82
github.com/multiplay/go/service.(*Service).Process(0xc00012b7d0, 0x0, 0x0, 0xc00012b7e0, 0xc000107140)
	/go/src/github.com/multiplay/go/service/service.go:123 +0x10c
github.com/multiplay/go/service.(*Generic).Run(0xc00012ef00, 0x0, 0x0)
	/go/src/github.com/multiplay/go/service/generic.go:228 +0x9c
github.com/multiplay/go/service.(*Generic).LoadConfigAndRun(0xc00012ef00, 0xc0000daf00, 0x155402a)
	/go/src/github.com/multiplay/go/service/generic.go:237 +0x67
github.com/multiplay/go/service.RunGeneric(0x1651720, 0xc0000daf00, 0x155402a, 0xa, 0x155b811, 0x14, 0x156ef68, 0x31, 0x1480d00, 0xc0001fa4e0)
	/go/src/github.com/multiplay/go/service/generic.go:145 +0xc5
main.main()
	/go/src/github.com/multiplay/go/apps/gameserver/gameserver.go:287 +0xd0
```

After using same machine, etc with only change bieing upgraded winsvc library everything worked ok

**Review by altrey — APPROVED** [review]

**Review by darkliquid — APPROVED** [review]
LGTM - kinda impossible to effectively review this but seems fine, especially virtually all changes are import reorders or new files.

**Review by danmrichards — APPROVED** [review]
Can't really do an effective review of this. But given the changes are coming from a trusted upstream, and there do not appear to be any conflicts or major red flags, probs fine

**Comment by lwaddicor** [comment]
Thank you all!

**Pull request merged**
